In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

/kaggle/input/voicegender/voice.csv

In [2]:
data =pd.read_csv('../input/voicegender/voice.csv')

In [3]:
data.head(500)

,meanfreq,sd,median,Q25,Q75,IQR,skew,kurt,sp.ent,sfm,...,centroid,meanfun,minfun,maxfun,meandom,mindom,maxdom,dfrange,modindx,label
0,0.059781,0.064241,0.032027,0.015071,0.090193,0.075122,12.863462,274.402906,0.893369,0.491918,...,0.059781,0.084279,0.015702,0.275862,0.007812,0.007812,0.007812,0.000000,0.000000,male
1,0.066009,0.067310,0.040229,0.019414,0.092666,0.073252,22.423285,634.613855,0.892193,0.513724,...,0.066009,0.107937,0.015826,0.250000,0.009014,0.007812,0.054688,0.046875,0.052632,male
2,0.077316,0.083829,0.036718,0.008701,0.131908,0.123207,30.757155,1024.927705,0.846389,0.478905,...,0.077316,0.098706,0.015656,0.271186,0.007990,0.007812,0.015625,0.007812,0.046512,male
3,0.151228,0.072111,0.158011,0.096582,0.207955,0.111374,1.232831,4.177296,0.963322,0.727232,...,0.151228,0.088965,0.017798,0.250000,0.201497,0.007812,0.562500,0.554688,0.247119,male
4,0.135120,0.079146,0.124656,0.078720,0.206045,0.127325,1.101174,4.333713,0.971955,0.783568,...,0.135120,0.106398,0.016931,0.266667,0.712812,0.007812,5.484375,5.476562,0.208274,male
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,0.200513,0.044940,0.209918,0.156009,0.230338,0.074329,2.319576,10.262777,0.898912,0.191798,...,0.200513,0.135308,0.056940,0.275862,0.468328,0.007812,5.468750,5.460938,0.084243,male
496,0.199620,0.042915,0.201954,0.165599,0.228469,0.062871,1.546042,6.143965,0.909862,0.190236,...,0.199620,0.136643,0.025397,0.275862,1.117188,0.164062,6.015625,5.851562,0.129935,male
497,0.202450,0.043619,0.206862,0.164668,0.231963,0.067295,1.431085,5.170582,0.906899,0.184218,...,0.202450,0.132458,0.017204,0.235294,0.640951,0.007812,4.789062,4.781250,0.089951,male
498,0.207534,0.051074,0.221954,0.154122,0.251533,0.097411,1.596567,6.751481,0.905324,0.188695,...,0.207534,0.131116,0.024353,0.275862,0.901042,0.156250,5.898438,5.742188,0.181803,male
499,0.140717,0.081793,0.137723,0.070793,0.221350,0.150557,1.686963,6.807624,0.966393,0.751094,...,0.140717,0.110489,0.017039,0.275862,0.398148,0.007812,5.046875,5.039062,0.116492,male

In [4]:
data.label.value_counts()

male      1584
female    1584
Name: label, dtype: int64

In [5]:
data.label=[1 if each == 'male' else 0 for each in data.label]
#data.diagnosis =[1 if each =='M' else 0 for each in data.diagnosis]

In [6]:
data.head()

,meanfreq,sd,median,Q25,Q75,IQR,skew,kurt,sp.ent,sfm,...,centroid,meanfun,minfun,maxfun,meandom,mindom,maxdom,dfrange,modindx,label
0,0.059781,0.064241,0.032027,0.015071,0.090193,0.075122,12.863462,274.402906,0.893369,0.491918,...,0.059781,0.084279,0.015702,0.275862,0.007812,0.007812,0.007812,0.000000,0.000000,1
1,0.066009,0.067310,0.040229,0.019414,0.092666,0.073252,22.423285,634.613855,0.892193,0.513724,...,0.066009,0.107937,0.015826,0.250000,0.009014,0.007812,0.054688,0.046875,0.052632,1
2,0.077316,0.083829,0.036718,0.008701,0.131908,0.123207,30.757155,1024.927705,0.846389,0.478905,...,0.077316,0.098706,0.015656,0.271186,0.007990,0.007812,0.015625,0.007812,0.046512,1
3,0.151228,0.072111,0.158011,0.096582,0.207955,0.111374,1.232831,4.177296,0.963322,0.727232,...,0.151228,0.088965,0.017798,0.250000,0.201497,0.007812,0.562500,0.554688,0.247119,1
4,0.135120,0.079146,0.124656,0.078720,0.206045,0.127325,1.101174,4.333713,0.971955,0.783568,...,0.135120,0.106398,0.016931,0.266667,0.712812,0.007812,5.484375,5.476562,0.208274,1

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3168 entries, 0 to 3167
Data columns (total 21 columns):
meanfreq    3168 non-null float64
sd          3168 non-null float64
median      3168 non-null float64
Q25         3168 non-null float64
Q75         3168 non-null float64
IQR         3168 non-null float64
skew        3168 non-null float64
kurt        3168 non-null float64
sp.ent      3168 non-null float64
sfm         3168 non-null float64
mode        3168 non-null float64
centroid    3168 non-null float64
meanfun     3168 non-null float64
minfun      3168 non-null float64
maxfun      3168 non-null float64
meandom     3168 non-null float64
mindom      3168 non-null float64
maxdom      3168 non-null float64
dfrange     3168 non-null float64
modindx     3168 non-null float64
label       3168 non-null int64
dtypes: float64(20), int64(1)
memory usage: 519.9 KB

In [8]:
x=data.drop(['label'],axis=1)#x =label haric diger kolonlar

In [9]:
y =data.iloc[:,-1:]#y= sadece son kolon =label kolonum

In [10]:
x =(x -np.min(x))/(np.max(x)-np.min(x)).values 
#verimi normalize ediyorum böylece kolonlar arası baglantı daha yakın oldugu için ögrenmem daha iyi oluyor ve sonucuda 
#test accuracy'im daha iyi sonuc çıkartıyor.

In [11]:
from sklearn.model_selection import train_test_split #verimi test,egitim diye bölüyorum
x_train,x_test,y_train,y_test =train_test_split(x,y,test_size=0.2,random_state=42)

In [12]:
#Logistic Regressor
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train)
print('test accuracy: {}'.format(lr.score(x_test,y_test)))
#test accuracy = y_head larımdan kaç tanesi y ile aynı =bunun oranının verir bana

test accuracy: 0.9810725552050473

/opt/conda/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/opt/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)