In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os
print(os.listdir("../input"))

# Any results you write to the current directory are saved as output.

['test.csv', 'train.csv']

In [2]:
data=pd.read_csv("../input/train.csv")
data.head()

   battery_power  blue     ...       wifi  price_range
0            842     0     ...          1            1
1           1021     1     ...          0            2
2            563     1     ...          0            2
3            615     1     ...          0            2
4           1821     1     ...          0            1

[5 rows x 21 columns]

In [3]:
x=data.drop(["price_range"],axis=1)
x.head()

   battery_power  blue  clock_speed  ...   three_g  touch_screen  wifi
0            842     0          2.2  ...         0             0     1
1           1021     1          0.5  ...         1             1     0
2            563     1          0.5  ...         1             1     0
3            615     1          2.5  ...         1             0     0
4           1821     1          1.2  ...         1             1     0

[5 rows x 20 columns]

In [4]:
y=data.price_range.values
y

array([1, 2, 2, ..., 3, 0, 3])

In [5]:
#Normalization
x=(x-np.min(x))/(np.max(x)-np.min(x))
x.head()

   battery_power  blue  clock_speed  ...   three_g  touch_screen  wifi
0       0.227789   0.0         0.68  ...       0.0           0.0   1.0
1       0.347361   1.0         0.00  ...       1.0           1.0   0.0
2       0.041416   1.0         0.00  ...       1.0           1.0   0.0
3       0.076152   1.0         0.80  ...       1.0           0.0   0.0
4       0.881764   1.0         0.28  ...       1.0           1.0   0.0

[5 rows x 20 columns]

In [6]:
from sklearn.model_selection import train_test_split
xTrain,xTest,yTrain,yTest=train_test_split(x,y,test_size=0.3,random_state=1)

In [7]:
from sklearn.tree import DecisionTreeClassifier
DTC=DecisionTreeClassifier()
DTC.fit(xTrain,yTrain)
print("Decision Tree Values: ",DTC.score(xTest,yTest))

Decision Tree Values:  0.8483333333333334

In [8]:
from sklearn.ensemble import RandomForestClassifier
RF=RandomForestClassifier(n_estimators=100,random_state=1)
RF.fit(xTrain,yTrain)
print("Random Forest Score: ",RF.score(xTest,yTest))

Random Forest Score:  0.8733333333333333