### About this Dataset
This database contains 76 attributes, The "goal" field refers to the presence of heart disease in the patient. It is integer valued from 0 (no presence) to 4.

### Attribute Features

* **age**: The person's age in years
* **sex**: The person's sex (1 = male, 0 = female)
* **cp**: The chest pain experienced (Value 1: typical angina, Value 2: atypical angina, Value 3: non-anginal pain, Value 4: asymptomatic)
* **trestbps**: The person's resting blood pressure (mm Hg on admission to the hospital)
* **chol**: The person's cholesterol measurement in mg/dl
* **fbs**: The person's fasting blood sugar (> 120 mg/dl, 1 = true; 0 = false)
* **restecg**: Resting electrocardiographic measurement (0 = normal, 1 = having ST-T wave abnormality, 2 = showing probable or definite left ventricular hypertrophy by Estes' criteria)
* **thalach**: The person's maximum heart rate achieved
* **exang**: Exercise induced angina (1 = yes; 0 = no)
* **oldpeak**: ST depression induced by exercise relative to rest ('ST' relates to positions on the ECG plot. See more here)
* **slope**: the slope of the peak exercise ST segment (Value 1: upsloping, Value 2: flat, Value 3: downsloping)
* **ca**: The number of major vessels (0-3)
* **thal**: A blood disorder called thalassemia (3 = normal; 6 = fixed defect; 7 = reversable defect)
* **target**: Heart disease (0 = no, 1 = yes)

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

/kaggle/input/heart-disease-uci/heart.csv

In [2]:
import pandas as pd
import numpy as np
heart = pd.read_csv("../input/heart-disease-uci/heart.csv")
heart.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

To look better we'll change the columns as given in attributes

In [3]:
heart.columns = ['Age', 'Sex', 'Chest_Pain_type', 'Resting_BP', 'Cholesterol', 'Fasting_Blood_Sugar', 'Rest_ECG', 'Max_Heart_Rate',
       'Exercise_Induced_Angina', 'ST_Depression', 'ST_Slope', 'No.of_Major_Vessels', 'Thalassemia', 'Target']
heart.head()
# looks better now

,Age,Sex,Chest_Pain_type,Resting_BP,Cholesterol,Fasting_Blood_Sugar,Rest_ECG,Max_Heart_Rate,Exercise_Induced_Angina,ST_Depression,ST_Slope,No.of_Major_Vessels,Thalassemia,Target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

Lets check the features of the data

In [4]:
heart.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
Age                        303 non-null int64
Sex                        303 non-null int64
Chest_Pain_type            303 non-null int64
Resting_BP                 303 non-null int64
Cholesterol                303 non-null int64
Fasting_Blood_Sugar        303 non-null int64
Rest_ECG                   303 non-null int64
Max_Heart_Rate             303 non-null int64
Exercise_Induced_Angina    303 non-null int64
ST_Depression              303 non-null float64
ST_Slope                   303 non-null int64
No.of_Major_Vessels        303 non-null int64
Thalassemia                303 non-null int64
Target                     303 non-null int64
dtypes: float64(1), int64(13)
memory usage: 33.3 KB

We can see there's no null values, looks like we have got a nice and clean data

### Now lets change the values for:

'sex'=0 & 1(0=Female, 1=Male), 

'Chest_Pain_type'= typical angina(1), atypical angina(2), non-anginal pain(3), asymptomatic(4)

'fasting_blood_sugar'= lower than 120mg/ml(0), greater than 120mg/ml(1)

'rest_ecg' = normal(0), ST-T wave abnormality(1), left ventricular hypertrophy(2)

'exercise_induced_angina' = no(0), yes(1)

'st_slope' = upsloping(1), flat(2), downsloping(3)

'thalassemia' = normal(1), fixed defect(2), reversable defect(3)

In [5]:
import warnings
warnings.filterwarnings("ignore")
heart['Sex'][heart['Sex'] == 0] = 'Female'
heart['Sex'][heart['Sex'] == 1] = 'Male'
heart['Chest_Pain_type'][heart['Chest_Pain_type'] == 1] = 'Typical Angina'
heart['Chest_Pain_type'][heart['Chest_Pain_type'] == 2] = 'aTypical Angina'
heart['Chest_Pain_type'][heart['Chest_Pain_type'] == 3] = 'Non-Anginal Pain'
heart['Chest_Pain_type'][heart['Chest_Pain_type'] == 4] = 'Asymptomatic'
heart['Fasting_Blood_Sugar'][heart['Fasting_Blood_Sugar'] == 0] = 'Lower than 120mg/ml'
heart['Fasting_Blood_Sugar'][heart['Fasting_Blood_Sugar'] == 1] = 'Greater than 120mg/ml'
heart['Rest_ECG'][heart['Rest_ECG'] == 0] = 'Normal'
heart['Rest_ECG'][heart['Rest_ECG'] == 1] = 'ST-T Wave Abnormality'
heart['Rest_ECG'][heart['Rest_ECG'] == 2] = 'Left Ventricular Hypertrophy'
heart['Exercise_Induced_Angina'][heart['Exercise_Induced_Angina'] == 0] = 'no'
heart['Exercise_Induced_Angina'][heart['Exercise_Induced_Angina'] == 1] = 'yes'
heart['ST_Slope'][heart['ST_Slope'] == 1] = 'Upsloping'
heart['ST_Slope'][heart['ST_Slope'] == 2] = 'Flat'
heart['ST_Slope'][heart['ST_Slope'] == 3] = 'Downsloping'
heart['Thalassemia'][heart['Thalassemia'] == 1] = 'Normal'
heart['Thalassemia'][heart['Thalassemia'] == 2] = 'Fixed defect'
heart['Thalassemia'][heart['Thalassemia'] == 3] = 'Reversable defect'

In [6]:
# import seaborn as sns
# sns.countplot(x='Sex', data=heart)
# sns.countplot(x='Chest_Pain_type', data=heart)
# sns.countplot(x='Fasting_Blood_Sugar', data=heart)
# sns.countplot(x='Rest_ECG', data=heart)
# sns.countplot(x='Exercise_Induced_Angina', data=heart)
# sns.countplot(x='ST_Slope', data=heart)
# sns.countplot(x='Thalassemia', data=heart)

In [7]:
heart.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
Age                        303 non-null int64
Sex                        303 non-null object
Chest_Pain_type            303 non-null object
Resting_BP                 303 non-null int64
Cholesterol                303 non-null int64
Fasting_Blood_Sugar        303 non-null object
Rest_ECG                   303 non-null object
Max_Heart_Rate             303 non-null int64
Exercise_Induced_Angina    303 non-null object
ST_Depression              303 non-null float64
ST_Slope                   303 non-null object
No.of_Major_Vessels        303 non-null int64
Thalassemia                303 non-null object
Target                     303 non-null int64
dtypes: float64(1), int64(6), object(7)
memory usage: 33.3+ KB

In [8]:
heart.head()

,Age,Sex,Chest_Pain_type,Resting_BP,Cholesterol,Fasting_Blood_Sugar,Rest_ECG,Max_Heart_Rate,Exercise_Induced_Angina,ST_Depression,ST_Slope,No.of_Major_Vessels,Thalassemia,Target
0,63,Male,Non-Anginal Pain,145,233,Greater than 120mg/ml,Normal,150,no,2.3,0,0,Normal,1
1,37,Male,aTypical Angina,130,250,Lower than 120mg/ml,ST-T Wave Abnormality,187,no,3.5,0,0,Fixed defect,1
2,41,Female,Typical Angina,130,204,Lower than 120mg/ml,Normal,172,no,1.4,Flat,0,Fixed defect,1
3,56,Male,Typical Angina,120,236,Lower than 120mg/ml,ST-T Wave Abnormality,178,no,0.8,Flat,0,Fixed defect,1
4,57,Female,0,120,354,Lower than 120mg/ml,ST-T Wave Abnormality,163,yes,0.6,Flat,0,Fixed defect,1

In [9]:
heart = pd.get_dummies(heart, drop_first=True)
heart.head()

,Age,Resting_BP,Cholesterol,Max_Heart_Rate,ST_Depression,No.of_Major_Vessels,Target,Sex_Male,Chest_Pain_type_Non-Anginal Pain,Chest_Pain_type_Typical Angina,Chest_Pain_type_aTypical Angina,Fasting_Blood_Sugar_Lower than 120mg/ml,Rest_ECG_Normal,Rest_ECG_ST-T Wave Abnormality,Exercise_Induced_Angina_yes,ST_Slope_Flat,ST_Slope_Upsloping,Thalassemia_Fixed defect,Thalassemia_Normal,Thalassemia_Reversable defect
0,63,145,233,150,2.3,0,1,1,1,0,0,0,1,0,0,0,0,0,1,0
1,37,130,250,187,3.5,0,1,1,0,0,1,1,0,1,0,0,0,1,0,0
2,41,130,204,172,1.4,0,1,0,0,1,0,1,1,0,0,1,0,1,0,0
3,56,120,236,178,0.8,0,1,1,0,1,0,1,0,1,0,1,0,1,0,0
4,57,120,354,163,0.6,0,1,0,0,0,0,1,0,1,1,1,0,1,0,0

### Splitting train and test data

In [10]:
X= heart.drop('Target',axis=1)
y=heart['Target']

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=.3,random_state=42)

In [12]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score
lr = LogisticRegression()
lr.fit(X_train, y_train)
lr_predict = lr.predict(X_test)
lr_confusion_matrix = confusion_matrix(y_test, lr_predict)
lr_accuracy_score = accuracy_score(y_test, lr_predict)
print(lr_confusion_matrix)
print(lr_accuracy_score)

[[33  8]
 [ 9 41]]
0.8131868131868132

In [13]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn import metrics
rf=RandomForestClassifier(n_estimators=250)
rf.fit(X_train,y_train)
Rfpred=rf.predict(X_test)
confusion_matrix(y_test, Rfpred)
metrics.accuracy_score(y_test,Rfpred)

0.8131868131868132

In [14]:
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix
model_SVC=SVC()
model_SVC.fit(X_train, y_train)
predictions=model_SVC.predict(X_test)
confusion_matrix(y_test, predictions)
classification_report(y_test,predictions,digits=4)
metrics.accuracy_score(y_test,predictions)

0.6923076923076923